### ISSUE TITLE
How to add the envelope icon in `text = "Click here to send an email !"`

### ISSUE THREAD

**Issue by gd047** [feddelegrand7/mailtoR#2]
I did this, but icon is not clickable

```
HTML("<i class='far fa-envelope'></i>"), mailtoR(email = "info@rstudio.com",
                                   text = "Click here to send an email !"),
```

**Comment by feddelegrand7** [comment]
hi @gd047, mailtoR is a wrapper of the javascript library mailtoUI, which I think (https://www.producthunt.com/posts/mailtoui-js) can only render texts to generate the mailing UI. I'm closing this issue, but if anyone has an idea on how to implement it, feel free to reopen.
